version: '3.5'

services:
  postgres:
    container_name: valoraechallenge
    image: postgres
    environment:
      POSTGRES_DB: valoraechallenge
      POSTGRES_USER: ${POSTGRES_USER:-valoraechallengeadmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-valoraechallengedb}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres: